---
# Collections required for the execution environment
collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=7.0.0"
  - name: community.docker
    version: ">=3.4.0"
  - name: community.crypto
    version: ">=2.15.0"
  - name: ansible.utils
    version: ">=2.10.0"

# If you need specific roles, add them here
# roles:
#   - name: geerlingguy.docker
#     version: ">=6.0.0"
