---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Test debug message from collection playbook"
      ansible.builtin.debug:
        msg: "Hello from my collection playbook!"
