---
driver:
  name: default

platforms:
  - name: localhost
    groups:
      - all

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          localhost:
            ansible_connection: local
            ansible_python_interpreter: "{{ ansible_playbook_python }}"
  config_options:
    defaults:
      stdout_callback: yaml
  playbooks:
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible
