---
name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Test Collection
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install ansible-core ansible-lint yamllint "molecule>=4" "molecule-plugins>=24"

      - name: Run linting
        run: |
          ansible-lint
          yamllint .

      - name: Run molecule tests
        run: molecule test

      - name: Build collection
        run: |
          cd padminisys.debug
          ansible-galaxy collection build
